// Generated by CoffeeScript 1.10.0
(function() {
  var base_url, createEvent, request;

  request = require('request');

  base_url = 'http://api.tenna.io';

  createEvent = function(device_id, kind, data, api_key, cb) {
    return request.post({
      url: base_url + "/devices/" + device_id + "/events/" + kind + ".json",
      form: data,
      json: true,
      headers: {
        'api_key': api_key
      }
    }, function(err, resp, body) {
      return cb(err, body);
    });
  };

  module.exports = function(arg) {
    var api_key, device_id;
    api_key = arg.api_key, device_id = arg.device_id;
    return {
      createEvent: function(kind, data, cb) {
        return createEvent(device_id, kind, data, api_key, cb);
      }
    };
  };

}).call(this);
