// Generated by CoffeeScript 1.10.0
(function() {
  var Tenna, base_url, request,
    slice = [].slice;

  request = require('request');

  base_url = 'http://api.tenna.io';

  Tenna = function(arg) {
    var api_key, default_headers, device_id;
    api_key = arg.api_key, device_id = arg.device_id;
    default_headers = {
      'api-key': api_key,
      'user-agent': 'Tenna API client'
    };
    return {
      createEvent: function(kind, data, cb) {
        return request.post({
          url: base_url + "/devices/" + device_id + "/events/" + kind + ".json",
          json: data,
          headers: default_headers
        }, function(err, resp, body) {
          return cb(err, body);
        });
      },
      sendCommand: function() {
        var args, cb, i, method;
        method = arguments[0], args = 3 <= arguments.length ? slice.call(arguments, 1, i = arguments.length - 1) : (i = 1, []), cb = arguments[i++];
        return request.post({
          url: base_url + "/devices/" + device_id + "/commands/" + method + ".json",
          json: args,
          headers: default_headers
        }, function(err, resp, body) {
          return cb(err, body);
        });
      },
      getState: function(cb) {
        return request.get({
          url: base_url + "/devices/" + device_id + "/state.json",
          headers: default_headers,
          json: true
        }, function(err, resp, body) {
          return cb(err, body);
        });
      }
    };
  };

  module.exports = Tenna;

}).call(this);
